spring:
  profiles:
    active: server

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging.level:
  org:
    hibernate:
      SQL: debug
#    apache:
#      coyote:
#        http11: debug

server:
  servlet:
    session:
      tracking-modes: COOKIE
